/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dealsAndPayments;

import adminPanelAndMainFrame.FirstFrame;
import static databaseStuffs.DatabaseMethods.con;
import static databaseStuffs.DatabaseMethods.connectDB;
import static databaseStuffs.DatabaseMethods.resultSet;
import static databaseStuffs.DatabaseMethods.statement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sirat
 */
public class RentDeal extends javax.swing.JFrame {

    String shopId = "";
    String tenantId = "";
    int counter = 0;

    /**
     * Creates new form rentDeal
     */
    public RentDeal() {
        initComponents();
        setLocationRelativeTo(null);
        dealButton.setVisible(false);
        setVisible(true);
        connectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        shopTextField = new javax.swing.JTextField();
        shopButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tenantTextField = new javax.swing.JTextField();
        tenantButton = new javax.swing.JButton();
        roomNoLabel = new javax.swing.JLabel();
        securityLabel = new javax.swing.JLabel();
        rentLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        referenceNameLabel = new javax.swing.JLabel();
        dealButton = new javax.swing.JButton();
        availablityLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rent Deal");
        setMinimumSize(new java.awt.Dimension(491, 351));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Shop ID: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 100, 20);
        getContentPane().add(shopTextField);
        shopTextField.setBounds(110, 30, 60, 30);

        shopButton.setBackground(new java.awt.Color(255, 255, 0));
        shopButton.setText("Check Availability");
        shopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopButtonActionPerformed(evt);
            }
        });
        getContentPane().add(shopButton);
        shopButton.setBounds(190, 30, 190, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tenant ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 140, 90, 20);

        tenantTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenantTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(tenantTextField);
        tenantTextField.setBounds(110, 140, 60, 30);

        tenantButton.setBackground(new java.awt.Color(255, 255, 0));
        tenantButton.setText("Check Availability");
        tenantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenantButtonActionPerformed(evt);
            }
        });
        getContentPane().add(tenantButton);
        tenantButton.setBounds(190, 140, 190, 23);

        roomNoLabel.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        roomNoLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(roomNoLabel);
        roomNoLabel.setBounds(200, 60, 240, 20);

        securityLabel.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        securityLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(securityLabel);
        securityLabel.setBounds(200, 90, 240, 20);

        rentLabel.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        rentLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(rentLabel);
        rentLabel.setBounds(200, 120, 240, 20);

        nameLabel.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(nameLabel);
        nameLabel.setBounds(200, 170, 240, 20);

        referenceNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        referenceNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(referenceNameLabel);
        referenceNameLabel.setBounds(200, 200, 240, 20);

        dealButton.setBackground(new java.awt.Color(204, 204, 255));
        dealButton.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        dealButton.setForeground(new java.awt.Color(0, 0, 102));
        dealButton.setText("Deal");
        dealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dealButton);
        dealButton.setBounds(180, 240, 130, 60);

        availablityLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        availablityLabel.setForeground(new java.awt.Color(51, 255, 0));
        getContentPane().add(availablityLabel);
        availablityLabel.setBounds(190, 10, 250, 40);

        iconLabel.setIcon(new javax.swing.ImageIcon("D:\\Project 2 Work\\Application\\Shopping Mall Management System\\Image\\background2.jpg")); // NOI18N
        getContentPane().add(iconLabel);
        iconLabel.setBounds(0, -30, 500, 370);

        homeMenu.setText("Home");
        homeMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                homeMenuMenuSelected(evt);
            }
        });
        jMenuBar1.add(homeMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tenantTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenantTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenantTextFieldActionPerformed

    private void shopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopButtonActionPerformed
        String idFromDB = "";
        String roomNo = "";
        String securityFee = "";
        String rent = "";
        shopId = shopTextField.getText();
        try {
            statement = con.createStatement();
            resultSet = statement.executeQuery("SELECT shop_id FROM `rent` WHERE shop_id=" + shopId);
            while (resultSet.next()) {
                idFromDB = resultSet.getString(1);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        if (!idFromDB.isEmpty() && idFromDB != null && idFromDB.matches(shopId)) {
            JOptionPane.showMessageDialog(this, "Shop is Not Available");
        } else {
            try {
                statement = con.createStatement();
                resultSet = statement.executeQuery("SELECT room_no,security_fee,rent FROM `shop` WHERE shop_id=" + shopId);
                while (resultSet.next()) {
                    roomNo = resultSet.getString(1);
                    securityFee = resultSet.getString(2);
                    rent = resultSet.getString(3);
                }
                if (!rent.isEmpty() && rent != null) {
                    roomNoLabel.setText("Room Number: " + roomNo);
                    securityLabel.setText("Security Fee:" + securityFee);
                    rentLabel.setText("Monthly Rent: " + rent);
                    shopButton.setVisible(false);
                    availablityLabel.setText("Shop Available...");
                    shopTextField.setEditable(false);
                    counter++;
                } else {
                    JOptionPane.showMessageDialog(this, "This Shop is Not Available!");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Enter Shop ID");
            }

        }
        if (counter >= 2) {
            dealButton.setVisible(true);
        }

    }//GEN-LAST:event_shopButtonActionPerformed

    private void homeMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_homeMenuMenuSelected
        new FirstFrame();
        this.dispose();
    }//GEN-LAST:event_homeMenuMenuSelected

    private void tenantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenantButtonActionPerformed

        String name = "";
        String referenceName = "";
        String referenceId = "";
        tenantId = tenantTextField.getText();
        try {
            statement = con.createStatement();
            resultSet = statement.executeQuery("SELECT name,reference_id FROM `tenant` WHERE tenant_id=" + tenantId);
            while (resultSet.next()) {
                name = resultSet.getString(1);
                referenceId = resultSet.getString(2);

            }
            resultSet = statement.executeQuery("SELECT name FROM `reference` WHERE reference_id=" + referenceId);
            while (resultSet.next()) {
                referenceName = resultSet.getString(1);
            }
            if (!name.isEmpty() && name != null) {
                nameLabel.setText("Tenant Name: " + name);
                referenceNameLabel.setText("Referenced Name: " + referenceName);
                tenantButton.setVisible(false);
                tenantTextField.setEditable(false);
                counter++;
            } else {
                JOptionPane.showMessageDialog(this, "This Tenant is Not Available!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Enter Valid Tenant ID");
        }

        if (counter >= 2) {
            dealButton.setVisible(true);
        }
    }//GEN-LAST:event_tenantButtonActionPerformed

    private void dealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealButtonActionPerformed
        new DealFinal(shopId, tenantId);
        this.dispose();

    }//GEN-LAST:event_dealButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentDeal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availablityLabel;
    private javax.swing.JButton dealButton;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel referenceNameLabel;
    private javax.swing.JLabel rentLabel;
    private javax.swing.JLabel roomNoLabel;
    private javax.swing.JLabel securityLabel;
    private javax.swing.JButton shopButton;
    private javax.swing.JTextField shopTextField;
    private javax.swing.JButton tenantButton;
    private javax.swing.JTextField tenantTextField;
    // End of variables declaration//GEN-END:variables
}
