package adminPanelAndMainFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sirat
 */
import databaseStuffs.DatabaseMethods.*;
import static databaseStuffs.DatabaseMethods.*;
import javax.swing.JOptionPane;
public class Setting_ChangeUsernamePassword extends javax.swing.JFrame {

    /**
     * Creates new form Setting_ChangeUsernamePassword
     */
    public Setting_ChangeUsernamePassword() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oldUsernameLabel = new javax.swing.JLabel();
        oldPasswordLabel = new javax.swing.JLabel();
        newUsernameLabel = new javax.swing.JLabel();
        newPasswordLabel = new javax.swing.JLabel();
        oldUsernameTextField = new javax.swing.JTextField();
        oldPasswordTextField = new javax.swing.JTextField();
        newUsernameTextField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        newPasswordTextField = new javax.swing.JTextField();
        changeButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        backMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change UserName And Password");

        oldUsernameLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        oldUsernameLabel.setText("Old Username");

        oldPasswordLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        oldPasswordLabel.setText("Old Password");

        newUsernameLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        newUsernameLabel.setText("New Username");

        newPasswordLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        newPasswordLabel.setText("New Password");

        oldUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldUsernameTextFieldActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(255, 0, 0));
        deleteButton.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 204, 0));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        changeButton.setBackground(new java.awt.Color(255, 204, 0));
        changeButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        changeButton.setText("Change");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        backMenu.setText("Back");
        backMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
                backMenuMenuCanceled(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                backMenuMenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                backMenuMenuSelected(evt);
            }
        });
        backMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(backMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changeButton)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newPasswordLabel)
                            .addComponent(newUsernameLabel)
                            .addComponent(oldPasswordLabel)
                            .addComponent(oldUsernameLabel))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oldPasswordTextField)
                            .addComponent(oldUsernameTextField)
                            .addComponent(newUsernameTextField)
                            .addComponent(newPasswordTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oldUsernameLabel)
                            .addComponent(oldUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oldPasswordLabel)
                            .addComponent(oldPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newUsernameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newUsernameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newPasswordLabel)
                    .addComponent(newPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(changeButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oldUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldUsernameTextFieldActionPerformed

    private void backMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backMenuActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        // UPDATE `shopping_mall_database`.`admin` SET `admin_id` = '2', `username` = '2', `password` = '2' WHERE `admin`.`admin_id` = 1
        String  oldUserName  = oldUsernameTextField.getText() ;
        String  oldPassword  =  oldPasswordTextField.getText();
        String  newUserName  =  newUsernameTextField.getText();
        String  newPassword  =  newPasswordTextField.getText();
        
        try{
            connectDB();
            statement = con.createStatement();         
            statement.execute("UPDATE `shopping_mall_database`.`admin` SET "
                    + "`username` = '"+newUserName+"', `password` = '"+newPassword+"' "
                    + "WHERE username='"+oldUserName+"' and password = '"+oldPassword+"'");
            closeDB();
            
            JOptionPane.showMessageDialog(this, "Admin's Information has Changed");
            FirstFrame FirstFrameObject = new FirstFrame();
            this.dispose();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Information is Not Correct!");
            e.printStackTrace();
        }
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_changeButtonActionPerformed

    private void backMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_backMenuMenuSelected
        new Setting();
        this.dispose();
    }//GEN-LAST:event_backMenuMenuSelected

    private void backMenuMenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_backMenuMenuDeselected
        // TODO add your handling code here:
    }//GEN-LAST:event_backMenuMenuDeselected

    private void backMenuMenuCanceled(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_backMenuMenuCanceled
        // TODO add your handling code here:
    }//GEN-LAST:event_backMenuMenuCanceled

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String  oldUserName  = oldUsernameTextField.getText() ;
        String  oldPassword  =  oldPasswordTextField.getText();
        new Setting_DeleteUser(oldUserName,oldPassword);
        this.dispose();
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      //  new Setting_ChangeUsernamePassword();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting_ChangeUsernamePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting_ChangeUsernamePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting_ChangeUsernamePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting_ChangeUsernamePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setting_ChangeUsernamePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu backMenu;
    private javax.swing.JButton changeButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JTextField newPasswordTextField;
    private javax.swing.JLabel newUsernameLabel;
    private javax.swing.JTextField newUsernameTextField;
    private javax.swing.JLabel oldPasswordLabel;
    private javax.swing.JTextField oldPasswordTextField;
    private javax.swing.JLabel oldUsernameLabel;
    private javax.swing.JTextField oldUsernameTextField;
    // End of variables declaration//GEN-END:variables
}
