package adminPanelAndMainFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sirat
 */
public class Setting extends javax.swing.JFrame {

    /**
     * Creates new form Setting
     */
    public Setting() {
        initComponents();
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addNewUserButton = new javax.swing.JButton();
        changeUsernamePasswordButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        backMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        addNewUserButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addNewUserButton.setForeground(new java.awt.Color(51, 51, 51));
        addNewUserButton.setText("Add New User");
        addNewUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addNewUserButton);
        addNewUserButton.setBounds(70, 130, 267, 53);

        changeUsernamePasswordButton.setBackground(new java.awt.Color(255, 204, 0));
        changeUsernamePasswordButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        changeUsernamePasswordButton.setForeground(new java.awt.Color(51, 51, 51));
        changeUsernamePasswordButton.setText("Update User Security");
        changeUsernamePasswordButton.setMaximumSize(new java.awt.Dimension(131, 25));
        changeUsernamePasswordButton.setMinimumSize(new java.awt.Dimension(131, 25));
        changeUsernamePasswordButton.setPreferredSize(new java.awt.Dimension(131, 25));
        changeUsernamePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUsernamePasswordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(changeUsernamePasswordButton);
        changeUsernamePasswordButton.setBounds(70, 30, 270, 58);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("  Warning: Deleting Account could be Dangerous ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 230, 330, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Project 2 Work\\Application\\Shopping Mall Management System\\Image\\CheckBackground.JPG")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -20, 400, 310);

        backMenu.setText("Back");
        backMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                backMenuMenuSelected(evt);
            }
        });
        backMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(backMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuActionPerformed
        FirstFrame FirstFrameObject = new FirstFrame();
        this.dispose();
    }//GEN-LAST:event_backMenuActionPerformed

    private void changeUsernamePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUsernamePasswordButtonActionPerformed
        Setting_ChangeUsernamePassword ob = new Setting_ChangeUsernamePassword();
        this.dispose();
    }//GEN-LAST:event_changeUsernamePasswordButtonActionPerformed

    private void addNewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewUserButtonActionPerformed
        Setting_AddNewUser ob = new Setting_AddNewUser();
        this.dispose();
    }//GEN-LAST:event_addNewUserButtonActionPerformed

    private void backMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_backMenuMenuSelected
        FirstFrame FirstFrameObject = new FirstFrame();
        this.dispose();
    }//GEN-LAST:event_backMenuMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewUserButton;
    private javax.swing.JMenu backMenu;
    private javax.swing.JButton changeUsernamePasswordButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
